#!/bin/bash
#TITLE: kbdled
#DESCRIPTION: Blink the Caps Lock key led using morse code
#AUTHOR: Raresteak
#VERSION: 0.1
#USAGE: ./kbdled "some text"
#DEPENDENCIES: xdotool package installed

# 
# Speed of the morse code
# .09 slower
# .05 faster
TIME=.09
# Do not make changes past this line.
Help () {
echo -e "NAME:
	 kbdled - Blink Caps Lock key 
	 Requires xdotool 
EXAMPLES: 
	./kbdled \"the quick brown fox jumps over the lazy dog\"
"
exit
}

Dash () {
  xdotool key Caps_Lock
  sleep $TIME
  sleep $TIME
  sleep $TIME
  xdotool key Caps_Lock
  sleep $TIME
}

Dot () {
  xdotool key Caps_Lock
  sleep $TIME
  xdotool key Caps_Lock
  sleep $TIME
}


which xdotool 1>/dev/null || Help

[[ "$#" -ne 1 ]] && Help

TEXT=$(echo $1 | tr [:lower:] [:upper:] | tr -cd A-Z0-9' ')
export DISPLAY=:0.0

COUNT="0"
while [ $COUNT -lt $[$(echo $TEXT | wc -c)-1] ] ; do
LETTER=${TEXT:$COUNT:1}
  case "$LETTER" in
  	A)
	Dot
	Dash
	;;
 	B)
	Dash
	Dot
	Dot
	Dot
	;;
	C)
	Dash
	Dot
	Dash
	Dot	
	;;
	D)
	Dash
	Dot
	Dot
	;;
	E)
	Dot
	;;
	F)
	Dot
	Dot
	Dash
	Dot
	;;
	G)
	Dash
	Dash
	Dot
	;;
	H)
	Dot
	Dot
	Dot
	Dot
	;;
	I)
	Dot
	Dot
	;;
	J)
	Dot
	Dash
	Dash
	Dash
	;;
	K)
	Dash
	Dot
	Dash
	;;
	L)
	Dot
	Dash
	Dot
	Dot
	;;
	M)
	Dash
	Dash
	;;
	N)
	Dash
	Dot
	;;
	O)
	Dash
	Dash
	Dash
	Dash
	;;
	P)
	Dot
	Dash
	Dash
	Dot
	;;
	Q)
	Dash
	Dash
	Dot
	Dash
	;;
	R)
	Dot
	Dash
	Dot
	;;
	S)
	Dot
	Dot
	Dot
	;;
	T)
	Dash
	;;
	U)
	Dot
	Dot
	Dash
	;;
	W)
	Dot
	Dash
	Dash
	;;
	X)
	Dash
	Dot
	Dot
	Dash
	;;
	Y)
	Dash
	Dot
	Dash
	Dash
	;;
	Z)
	Dash
	Dash
	Dot
	Dot
	;;
	1)
	Dot
	Dash
	Dash
	Dash
	Dash
	;;
	2)
	Dot
	Dot
	Dash
	Dash
	Dash
	;;
	3)
	Dot
	Dot
	Dot
	Dash
	Dash
	;;
	4)
	Dot
	Dot
	Dot
	Dot
	Dash
	;;
	5)
	Dot
	Dot
	Dot
	Dot
	Dot
	;;
	6)
	Dash
	Dot
	Dot
	Dot
	Dot
	;;
	7)
	Dash
	Dash
	Dot
	Dot
	Dot
	;;
	8)
	Dash
	Dash
	Dash
	Dot
	Dot
	;;
	9)
	Dash
	Dash
	Dash
	Dash
	Dot
	;;
	0)
	Dash
	Dash
	Dash
	Dash
	Dash
	;;
	*)
	Dot
	;;
  esac
  COUNT=$[$COUNT+1]
done



