#!/bin/bash
#TITLE: kbdled
#DESCRIPTION: Blink a keyboard led key using Morse Code
#AUTHOR: Raresteak
#VERSION: 0.4
#USAGE: ./kbdled "some text"
#DEPENDENCIES: xdotool package installed

# 
# Speed of the morse code
# .09 slower
# .05 faster
TIME=.05
# Led to blink
# Num_Lock, Caps_Lock, Scroll_Lock
KEY="Num_Lock"
# Do not make changes past this line.
Help () {
echo -e "NAME:
	 kbdled - Blink Caps Lock, Num Lock, or Scroll keys
REQUIRES: 
	 xdotool package
EXAMPLES: 
	./kbdled \"the quick brown fox jumps over the lazy dog\"
"
exit
}

Dash () {
  xdotool key $KEY
  sleep $TIME
  sleep $TIME
  sleep $TIME
  xdotool key $KEY
  sleep $TIME
}

Dot () {
  xdotool key $KEY
  sleep $TIME
  xdotool key $KEY
  sleep $TIME
}


which xdotool 1>/dev/null || Help

[[ "$#" -ne 1 ]] && Help

TEXT=$(echo $1 | tr [:lower:] [:upper:] | tr -cd A-Z0-9' ')


COUNT="0"
while [ $COUNT -lt $[$(echo $TEXT | wc -c)-1] ] ; do
LETTER=${TEXT:$COUNT:1}
  case "$LETTER" in
  	A)
	Dot
	Dash
	;;
 	B)
	Dash
	Dot
	Dot
	Dot
	;;
	C)
	Dash
	Dot
	Dash
	Dot	
	;;
	D)
	Dash
	Dot
	Dot
	;;
	E)
	Dot
	;;
	F)
	Dot
	Dot
	Dash
	Dot
	;;
	G)
	Dash
	Dash
	Dot
	;;
	H)
	Dot
	Dot
	Dot
	Dot
	;;
	I)
	Dot
	Dot
	;;
	J)
	Dot
	Dash
	Dash
	Dash
	;;
	K)
	Dash
	Dot
	Dash
	;;
	L)
	Dot
	Dash
	Dot
	Dot
	;;
	M)
	Dash
	Dash
	;;
	N)
	Dash
	Dot
	;;
	O)
	Dash
	Dash
	Dash
	Dash
	;;
	P)
	Dot
	Dash
	Dash
	Dot
	;;
	Q)
	Dash
	Dash
	Dot
	Dash
	;;
	R)
	Dot
	Dash
	Dot
	;;
	S)
	Dot
	Dot
	Dot
	;;
	T)
	Dash
	;;
	U)
	Dot
	Dot
	Dash
	;;
	W)
	Dot
	Dash
	Dash
	;;
	X)
	Dash
	Dot
	Dot
	Dash
	;;
	Y)
	Dash
	Dot
	Dash
	Dash
	;;
	Z)
	Dash
	Dash
	Dot
	Dot
	;;
	1)
	Dot
	Dash
	Dash
	Dash
	Dash
	;;
	2)
	Dot
	Dot
	Dash
	Dash
	Dash
	;;
	3)
	Dot
	Dot
	Dot
	Dash
	Dash
	;;
	4)
	Dot
	Dot
	Dot
	Dot
	Dash
	;;
	5)
	Dot
	Dot
	Dot
	Dot
	Dot
	;;
	6)
	Dash
	Dot
	Dot
	Dot
	Dot
	;;
	7)
	Dash
	Dash
	Dot
	Dot
	Dot
	;;
	8)
	Dash
	Dash
	Dash
	Dot
	Dot
	;;
	9)
	Dash
	Dash
	Dash
	Dash
	Dot
	;;
	0)
	Dash
	Dash
	Dash
	Dash
	Dash
	;;
	*)
	Dot
	;;
  esac
  COUNT=$[$COUNT+1]
done



